### ISSUE TITLE
[bug] Issues Federating with Mastodon Instances with different WEB_DOMAIN and LOCAL_DOMAIN

### ISSUE THREAD

**Issue by theokeeler** [superseriousbusiness/gotosocial#1445]
### Describe the bug with a clear and concise description of what the bug is.

I'm unable to follow two different publically followable accounts on two different servers that are set up with their mastodon WEB_DOMAIN set to a different subdomain than their LOCAL_DOMAIN - i.e. they are on social.example.com or mastodon.example.com, but handles are presented as being on example.com itself. Both servers I've found this behaviour with are running Mastodon 4.0.2.

### What's your GoToSocial Version?

0.6.0

### GoToSocial Arch

x64 Docker

### What happened?

I sent follow requests for two accounts on split WEB_DOMAIN/LOCAL_DOMAIN mastodon instances; From a client, these requests send, and then sit in pending indefinitely. In the log, I eventually recieve a 401 Unauthorized "message processing error" response.

### What you expected to happen?

I expected to follow the accounts as normal.

### How to reproduce it?

The two accounts I know to be set up this way, and that I can reliably get to behave this way, are `@notjustbikes@notjustbikes.com` and `@strangeparts@strangeparts.com`. Attempting to follow either from GoToSocial (at least my instance) results in this failure 100% of the time.

### Anything else we need to know?

It's possible my server first saw both of these servers prior to them setting up their accounts with a separate WEB_DOMAIN/LOCAL_DOMAIN - I vaguely recall looking them both up the first time with their full subdomains, but I can't guarantee I am remembering correctly. I'm happy to try this with any similarly set up accounts to see if this behaviour remains and perhaps confirm or deny that this is the case.

**Comment by NyaaaWhatsUpDoc** [comment]
There have been changes to the handling of this in the latest v0.7.0, so there is a chance this could be fixed there. I'm running the latest RC myself and had no issue in following those accounts. If you feel comfortable updating to the latest RC then I would encourage it, but if not then it will probably be better from a bug-hunting aspect to confirm this still exists once you have updated to the full release version of v0.7.0 :)

**Comment by theokeeler** [comment]
I just gave this a try on 0.7.0-rc1 and I'm seeing the same problem.

**Comment by tsmethurst** [comment]
I can follow the first one OK from goblin.technology.

In the case of that second one, I get a 404 from trying to webfinger the account (`https://strangeparts.com/.well-known/webfinger?resource=acct:strangeparts@strangeparts.com`), so I don't think that's a GtS problem.

We'll release rc2 shortly-ish, and that has a couple fixes in there for accounts with different host/account domains, so I think it'll be worth trying that too and seeing if it fixes the issue for ya.

**Comment by theokeeler** [comment]
Tried this again on rc2; Same behaviour as before.

**Comment by daenney** [comment]
OK, so these particular instances are a bit wobbly in its configuration. This is honestly an instance configuration issue because redirecting webfinger through host-meta instead of an HTTP redirect is not the recommended way of doing things anymore.

### strangeparts.com

* Expected webfinger endpoint fails:
   ```
   $  curl -I 'https://strangeparts.com/.well-known/webfinger'
       HTTP/2 404 
   ```
This is why GtS currently fails. With #1588 we'll do the fallback discovery
* Discover host-meta:
   ```
   curl -I 'https://strangeparts.com/.well-known/host-meta'
   HTTP/2 301 
   location: https://mastodon.strangeparts.com/.well-known/host-meta
   ```
* Yay it responds, a redirect though :roll_eyes:  so then we try:
   ```
   $ curl -X GET 'https://mastodon.strangeparts.com/.well-known/host-meta'
   <?xml version="1.0" encoding="UTF-8"?>
   <XRD xmlns="http://docs.oasis-open.org/ns/xri/xrd-1.0">
     <Link rel="lrdd" template="https://mastodon.strangeparts.com/.well-known/webfinger?resource={uri}"/>
   </XRD>
   ```

And now we finally have the right webfinger endpoint which we'll try. I've implemented the fallback detection mechanism in #1588 which will solve this issue with this instance.

### notjustbikes.com

This one should work currently:
```
$ curl -I 'https://notjustbikes.com/.well-known/webfinger'
HTTP/1.1 301 Moved Permanently
Location: https://social.notjustbikes.com/.well-known/webfinger
```

```
$ curl -L -XGET 'https://notjustbikes.com/.well-known/webfinger?resource=notjustbikes@notjustbikes.com' | jq .
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   178  100   178    0     0    395      0 --:--:-- --:--:-- --:--:--   395
100   530    0   530    0     0    941      0 --:--:-- --:--:-- --:--:--   941
{
  "subject": "acct:notjustbikes@notjustbikes.com",
  "aliases": [
    "https://social.notjustbikes.com/@notjustbikes",
    "https://social.notjustbikes.com/users/notjustbikes"
  ],
  "links": [
    {
      "rel": "http://webfinger.net/rel/profile-page",
      "type": "text/html",
      "href": "https://social.notjustbikes.com/@notjustbikes"
    },
    {
      "rel": "self",
      "type": "application/activity+json",
      "href": "https://social.notjustbikes.com/users/notjustbikes"
    },
    {
      "rel": "http://ostatus.org/schema/1.0/subscribe",
      "template": "https://social.notjustbikes.com/authorize_interaction?uri={uri}"
    }
  ]
}
```

Maybe they've fixed whatever was ailing it in the mean time, but at least it's unrelated to the host-meta fallback thing.

**Comment by theokeeler** [comment]
Hey, thanks for following up on this.

I'll set a reminder for myself to give the first of those two a retry once #1588 is in a release/rc.

The second one is still failing for me on 0.7.1 - is there any additional debug info/logging I can get you that might point to what's going on here? I'm still leaning towards "my instance first saw this on social.notjustbikes.com and then it moved to notjustbikes.com proper and now something's confused" but I have no solid evidence thereof.

**Comment by daenney** [comment]
Ahhh. That sure sounds like it might have gotten confused. I'm not sure about how to clear that out... I would imagine it requires yeeting some entries out of the DB but I wouldn't dare tell you what. I'll leave that to @tsmethurst or @NyaaaWhatsUpDoc.

**Comment by theokeeler** [comment]
Just checked this on 0.9.0 - still having the same behaviour on both accounts, so I assume something in my instance's database is in fact at fault here.

Looking at my logs, I'm seeing what I think is a 401 being returned from my server to these remotes when they try to hit /users/gopher, so if my wild guessing is correct I think there's some some sort of issue with the key my server is expecting from these servers vs what's showing up on that request. Is there somewhere I can start poking in the DB to try to purge my server's knowledge of these servers (or ones that suffer a similar fate)?

**Comment by tsmethurst** [comment]
Hey @theokeeler, is this still an issue?

If so, expiring keys for domains that are 401'ing might help (https://github.com/superseriousbusiness/gotosocial/pull/2183)

**Comment by theokeeler** [comment]
Yep, this is still happening for me on 0.11.1. Once #2183 is in I'll give that a try.

**Comment by theokeeler** [comment]
Gave expiring these domains' keys a try in 0.12.0-rc2; No change in behaviour after expiring both the display domain and the subdomain for either account.

**Comment by tsmethurst** [comment]
Hmm, at this point you might have better luck just yeeting everything from that domain and trying again. Can you try domain blocking `social.notjustbikes.com` and `notjustbikes.com`, expiring keys for both domains, and then removing the domain blocks again?

**Comment by theokeeler** [comment]
After a block/expire/un-block cycle, the problem persists; I can see that posts from both problem accounts that were previously boosted into my timeline are now absent, so I'd assume the block part of that operation did at least manage to wipe all posts. Given that, I'm at something of a loss; Could my server have potentially sent something in the past that's making the remote stuck, rather than this being something I can fix from my end?

**Comment by tsmethurst** [comment]
To be honest at this point my assumption would be that it's something on their side that's giving the 401, perhaps because your keys changed at some point, or some other weirdness happens. What if you try making a new user on your instance and sending the request from that user?

**Comment by theokeeler** [comment]
On a whim I tried refollowing these accounts on 0.15.0 and it works perfectly now, so I'm going to close this issue. Not sure what exactly changed (on either side of this equation), but whatever it is seems fixed.
